kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: daemonset-depl-nginx
  namespace:  nginx-namesapce
spec:
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      name: nginx-template-for-pod
      labels:
        app: nginx

    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

